// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


describe('Form Select Checkbox', function() {
this.timeout(30000)
let driver
let vars

beforeEach(async function() {
  driver = await new Builder().forBrowser('chrome').build()
  vars = {}
})
afterEach(async function() {
  await driver.quit();
})
  it('Selenium test page', async function() {
    // Open window
    await driver.get("https://automationintesting.com/selenium/testpage/")
    // Set window size
    await driver.manage().window().setRect({ width: 1680, height: 940 })
    // Press first name
    await driver.findElement(By.id("firstname")).click()
    // Type first name
    await driver.findElement(By.id("firstname")).sendKeys("Bob")
    // Type surname
    await driver.findElement(By.id("surname")).sendKeys("Sapp")
    // Click gender
    await driver.findElement(By.id("gender")).click()
    // Click select
{
  const dropdown = await driver.findElement(By.id("gender"))
  await dropdown.findElement(By.xpath("//option[. = 'My Business!']")).click()
}
await driver.findElement(By.id("blue")).click()
await driver.findElement(By.css("textarea")).click()
await driver.findElement(By.css("textarea")).sendKeys("more stuff")
// Select from dropdown
{
  const element = await driver.findElement(By.id("continent"))
  await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
}
{
  const element = await driver.findElement(By.id("continent"))
  await driver.actions({ bridge: true }).moveToElement(element).perform()
}
{
  const element = await driver.findElement(By.id("continent"))
  await driver.actions({ bridge: true }).moveToElement(element).release().perform()
}
{
  const dropdown = await driver.findElement(By.id("continent"))
  await dropdown.findElement(By.xpath("//option[. = 'Europe']")).click()
}
  })
})
