# Generated by Selenium IDE
import json
import time

import pytest

from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait


class TestChecks:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_pluginCommands(self):
        self.driver.get("undefined/webhp")
        print("This is a test string")
        self.driver.find_element(By.CSS_SELECTOR, ".lnXdpd").click()
        self.driver.find_element(By.NAME, "q").send_keys("selenium ide")
        self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
        self.driver.find_element(By.CSS_SELECTOR, ".g a").click()
        assert (
            self.driver.title ==
            "Selenium IDE · Open source record and playback test automation for the web"
        )
